[pr_description]
enable_help_text=false

[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = false
maximal_review_effort = 0
enable_help_text=false
num_code_suggestions=3

[github_app]
pr_commands = [
    "/describe",
    "/review",
  ]

[pr_code_suggestions]
commitable_code_suggestions=false
num_code_suggestions=0
rank_suggestions=true
enable_help_text=false
