[pr_description]
enable_help_text=false

[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = false
maximal_review_effort = 2
# enable_help_text=false

[github_app]
pr_commands = [
    "/describe",
    "/reflect_and_review --pr_reviewer.num_code_suggestions=3",
    "/improve",
    "/update_changelog",
    "/analyze"
  ]

[pr_code_suggestions]
commitable_code_suggestions=true
num_code_suggestions=4
rank_suggestions=true
# enable_help_text=false
