[config]
enable_auto_approval=false
add_repo_metadata = true

[pr_description]
enable_help_text=false

[pr_reviewer]
enable_review_labels_effort=true
enable_help_text=false


[github_app]
pr_commands = [
    "/review",
]

[pr_code_suggestions]
commitable_code_suggestions=false
num_code_suggestions=0
enable_help_text=false
suggestions_score_threshold=8

[checks]
enable_auto_checks_feedback=false
persistent_comment=false
enable_help_text=false
